language: go
sudo: required
services:
  - docker
install:
  - go get github.com/gin-gonic/gin
before_script:
  # Set Jira issue key for post build actions
  - export JIRA_ISSUE=`git log --pretty="%s" $TRAVIS_COMMIT_RANGE|sed -n 's/.*\(SAVA-[0-9]*\)\ \.*/\1/p'`
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - cd $TRAVIS_BUILD_DIR
script: docker/build.sh $TRAVIS_BUILD_NUMBER
notifications:
  webhooks:
#    - https://$JIRA_USER:$JIRA_PASS@89.31.102.182/rest/api/latest/$JIRA_ISSUE
  - http://89.31.102.182/rest/api/latest/$JIRA_ISSUE
