language: go
sudo: required
services:
  - docker
install:
  - go get github.com/gin-gonic/gin
before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - cd $TRAVIS_BUILD_DIR
script: docker/build.sh $TRAVIS_BUILD_NUMBER
