language: go
sudo: false
install:
  - apt-get install libc6-dev-i386
  - export GOROOT=`go env GOROOT`
  - export GOHOSTARCH="386"
  - cd $GOROOT/src/;./make.bash
  - go get github.com/gin-gonic/gin
before_script:
  - cd $TRAVIS_BUILD_DIR
script: docker/build.sh $TRAVIS_BUILD_NUMBER
